version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: beautymaker_db
    environment:
      POSTGRES_DB: beautymaker
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local 
