package com.doo.finalActv.beautymaker.ui.client;

import java.util.ArrayList;
import javax.swing.Box;
import javax.swing.JPanel;

public class CardListView<T extends JPanel> extends javax.swing.JPanel {

  private ArrayList<T> cardListPanels;
  private String title;

  public CardListView(String title) {
    initComponents();
    this.cardListPanels = new ArrayList<>();
    this.title = title;

    this.initializeView();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    titleLabel = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    cardContainer = new javax.swing.JPanel();

    setPreferredSize(new java.awt.Dimension(1000, 1000));

    titleLabel.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
    titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

    cardContainer.setLayout(new javax.swing.BoxLayout(cardContainer, javax.swing.BoxLayout.Y_AXIS));
    jScrollPane1.setViewportView(cardContainer);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
          .addComponent(titleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 882, Short.MAX_VALUE)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel cardContainer;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel titleLabel;
  // End of variables declaration//GEN-END:variables

  public void initializeView() {
    if(this.title != null && !this.title.isEmpty()) {
      this.titleLabel.setText(this.title);
    } else {
      this.titleLabel.setText("Card List");
    }
  }

  public void updateCardList(ArrayList<T> cardList) {
    this.cardListPanels = cardList;
    this.cardContainer.removeAll();
    this.cardContainer.add(Box.createVerticalStrut(20));

    for (JPanel card : cardList) {
      this.cardContainer.add(card);
      this.cardContainer.add(Box.createVerticalStrut(20));
    }

    this.cardContainer.revalidate();
    this.cardContainer.repaint();
  }
}
