package com.doo.finalActv.beautymaker.ui.client;

import com.doo.finalActv.beautymaker.model.ServiceData;
import com.doo.finalActv.beautymaker.serivce.appdata.ContentProvider;
import com.doo.finalActv.beautymaker.serivce.appdata.DataChangeListener;
import com.doo.finalActv.beautymaker.ui.client.cards.ServiceCard;
import java.util.ArrayList;
import javax.swing.Box;
import javax.swing.JLabel;

public class ServicesView extends javax.swing.JPanel implements DataChangeListener {

  public ServicesView() {
    initComponents();

    this.initialize();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    serviceContainerPanel = new javax.swing.JPanel();

    setPreferredSize(new java.awt.Dimension(1000, 1000));

    jLabel1.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Services");

    serviceContainerPanel.setLayout(new javax.swing.BoxLayout(serviceContainerPanel, javax.swing.BoxLayout.Y_AXIS));
    jScrollPane1.setViewportView(serviceContainerPanel);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
          .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 882, Short.MAX_VALUE)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JPanel serviceContainerPanel;
  // End of variables declaration//GEN-END:variables

  private void initialize() {
    ContentProvider.getInstance().addListener(this, "services");
  }

  @Override
  public void onDataChanged() {
    ArrayList<ServiceData> services = ContentProvider.getInstance().getServices();
    serviceContainerPanel.removeAll();
    serviceContainerPanel.add(Box.createVerticalStrut(20));
    for (ServiceData service : services) {
      ServiceCard serviceCard = new ServiceCard(service);
      serviceContainerPanel.add(serviceCard);
      serviceContainerPanel.add(Box.createVerticalStrut(20));
    }
    if (services.isEmpty()) {
      JLabel noServiceLabel = new javax.swing.JLabel("No services available");
      serviceContainerPanel.add(noServiceLabel);
    }
    serviceContainerPanel.revalidate();
    serviceContainerPanel.repaint();
  }

}
