package com.doo.finalActv.beautymaker.ui;

import com.doo.finalActv.beautymaker.model.MenuEntry;
import com.doo.finalActv.beautymaker.model.User;
import com.doo.finalActv.beautymaker.serivce.appdata.ContentProvider;
import com.doo.finalActv.beautymaker.serivce.event.EventManager;
import com.doo.finalActv.beautymaker.serivce.event.model.MenuItemSelectedEvent;
import com.doo.finalActv.beautymaker.serivce.event.model.RequestLogoutEvent;
import com.doo.finalActv.beautymaker.ui.client.AppointmentsView;
import com.doo.finalActv.beautymaker.ui.client.ProfileView;
import com.doo.finalActv.beautymaker.ui.client.ServicesView;
import com.doo.finalActv.beautymaker.ui.client.StaffView;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.JComponent;

import com.doo.finalActv.beautymaker.ui.customComponents.LogoHome;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

abstract class BaseHomeView extends javax.swing.JInternalFrame {
  protected MenuEntry[] menuEntries;

  public BaseHomeView(MenuEntry[] menuEntries) {
    initComponents();
    this.menuEntries = menuEntries;
    this.initialize();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelMenu = new javax.swing.JPanel();
    panelView = new javax.swing.JPanel();

    panelMenu.setBackground(new java.awt.Color(153, 153, 153));
    panelMenu.setAlignmentY(0.0F);
    panelMenu.setMaximumSize(new java.awt.Dimension(240, 1044));
    panelMenu.setPreferredSize(new java.awt.Dimension(240, 1044));
    panelMenu.setLayout(new javax.swing.BoxLayout(panelMenu, javax.swing.BoxLayout.Y_AXIS));

    panelView.setBackground(new java.awt.Color(102, 102, 102));
    panelView.setAlignmentX(0.0F);
    panelView.setAlignmentY(0.0F);
    panelView.setLayout(new javax.swing.BoxLayout(panelView, javax.swing.BoxLayout.LINE_AXIS));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, 0)
        .addComponent(panelView, javax.swing.GroupLayout.DEFAULT_SIZE, 1268, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
      .addComponent(panelView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel panelMenu;
  private javax.swing.JPanel panelView;
  // End of variables declaration//GEN-END:variables

  private void initialize() {
    this.setupMenu();
    this.setupAppearance();
  }

  private void setupMenu() {
    this.addLogo();
    this.setupMenuListener();
    this.addMenuItems();
    this.addLogoutBtn();

    this.selectInitialMenuEntry();
  }

  protected void selectMenuEntry(String key) {
    EventManager.getInstance().publish(new MenuItemSelectedEvent(key));
  }

  private void addLogo() {
    this.panelMenu.add(new LogoHome());
    this.panelMenu.add(javax.swing.Box.createVerticalStrut(20));
    String wellcomeText = "Welcome";
    User user = ContentProvider.getInstance().getUser();
    if(user != null) {
      wellcomeText += ", " + user.getName();
    }
    JLabel welcomeLabel = new JLabel(wellcomeText);
    welcomeLabel.setFont(new java.awt.Font("Arial", 1, 18));
    welcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
    welcomeLabel.setAlignmentX(JLabel.CENTER_ALIGNMENT);
    welcomeLabel.setAlignmentY(JLabel.CENTER_ALIGNMENT);
    welcomeLabel.setHorizontalAlignment(JLabel.CENTER);


    this.panelMenu.add(javax.swing.Box.createVerticalStrut(20));
    this.panelMenu.add(welcomeLabel);
    this.panelMenu.add(javax.swing.Box.createVerticalStrut(20));
  }

  private void setupMenuListener() {
    EventManager.getInstance().subscribe(MenuItemSelectedEvent.class, event -> {
      String key = event.menuTitle;
      for (MenuEntry entry : this.menuEntries) {
        if (entry.getKey().equals(key)) {
          entry.select();
          this.panelView.removeAll();
          this.panelView.add(entry.getViewPanel());
          this.panelView.revalidate();
          this.panelView.repaint();
        } else {
          entry.unselect();
        }
      }
    });

  }

  private void addMenuItems() {
    for (MenuEntry entry : this.menuEntries) {
      JPanel entryPanel = entry.getMenuPanel();
      entryPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
      this.panelMenu.add(entryPanel);
    }
  }

  private void selectInitialMenuEntry() {
    // Select the first menu entry by default
    EventManager.getInstance().publish(new MenuItemSelectedEvent(
      this.menuEntries[0].getKey()
    ));
  }

  private void setupAppearance() {
    putClientProperty("JInternalFrame.isPalette", Boolean.TRUE);
    setRootPaneCheckingEnabled(false);

    if (getUI() instanceof BasicInternalFrameUI basicUI) {
      basicUI.setNorthPane(null);
    }
    setResizable(false);
    setOpaque(false);
    getRootPane().setOpaque(false);
    ((JComponent) getContentPane()).setOpaque(false);
    setBorder(null);
    setFrameIcon(null);

    this.revalidate();
    this.repaint();
  }

  private void addLogoutBtn() {
    
    JButton logoutButton = new JButton("Logout");
    logoutButton.setAlignmentX(JButton.CENTER_ALIGNMENT);
    logoutButton.addActionListener(e -> {
      EventManager.getInstance().publish(new RequestLogoutEvent());
    });
    logoutButton.setVisible(true);

    this.panelMenu.add(javax.swing.Box.createVerticalStrut(50));
    this.panelMenu.add(logoutButton);
    this.panelMenu.revalidate();
    this.panelMenu.repaint();
  }
}
