package com.doo.finalActv.beautymaker.ui;

import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.JComponent;

import com.doo.finalActv.beautymaker.ui.customComponents.LogoHome;

public class BaseHomeView extends javax.swing.JInternalFrame {

  public BaseHomeView() {
    initComponents();

    this.initialise();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelMenu = new javax.swing.JPanel();
    panelView = new javax.swing.JPanel();

    panelMenu.setBackground(new java.awt.Color(153, 153, 153));
    panelMenu.setAlignmentY(0.0F);
    panelMenu.setMaximumSize(new java.awt.Dimension(240, 1044));
    panelMenu.setPreferredSize(new java.awt.Dimension(240, 1044));
    panelMenu.setLayout(new javax.swing.BoxLayout(panelMenu, javax.swing.BoxLayout.Y_AXIS));

    panelView.setBackground(new java.awt.Color(102, 102, 102));
    panelView.setAlignmentX(0.0F);
    panelView.setAlignmentY(0.0F);

    javax.swing.GroupLayout panelViewLayout = new javax.swing.GroupLayout(panelView);
    panelView.setLayout(panelViewLayout);
    panelViewLayout.setHorizontalGroup(
      panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 1262, Short.MAX_VALUE)
    );
    panelViewLayout.setVerticalGroup(
      panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 1044, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, 0)
        .addComponent(panelView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addComponent(panelView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel panelMenu;
  private javax.swing.JPanel panelView;
  // End of variables declaration//GEN-END:variables

  private void initialise() {
    this.panelMenu.add(new LogoHome());
    
    this.setupFrameAppearance();
    this.revalidate();
    this.repaint();
  }

  private void setupFrameAppearance() {
    putClientProperty("JInternalFrame.isPalette", Boolean.TRUE);
    setRootPaneCheckingEnabled(false);

    if (getUI() instanceof BasicInternalFrameUI basicUI) {
      basicUI.setNorthPane(null);
    }
    setResizable(false);
    setOpaque(false);
    getRootPane().setOpaque(false);
    ((JComponent) getContentPane()).setOpaque(false);
    setBorder(null);
  }
}
