package com.doo.finalActv.beautymaker.ui.customComponents;

import com.doo.finalActv.beautymaker.serivce.event.EventManager;
import com.doo.finalActv.beautymaker.serivce.event.model.MenuItemSelectedEvent;
import java.awt.Color;

public class MenuCardPanel extends javax.swing.JPanel {
  private String title;
  private Color crrColor;
  private Color hoverColor;
  private boolean isSelected = false;
  private boolean isHovered = false;

  public MenuCardPanel(String title) { 
    initComponents();
    this.title = title;
    this.initialize();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    titlePanel = new javax.swing.JLabel();
    iconPanel = new javax.swing.JLabel();

    setBackground(new java.awt.Color(153, 153, 153));
    setMaximumSize(new java.awt.Dimension(220, 60));
    setMinimumSize(new java.awt.Dimension(220, 60));
    setPreferredSize(new java.awt.Dimension(220, 60));

    titlePanel.setBackground(new java.awt.Color(153, 153, 153));
    titlePanel.setFont(new java.awt.Font("Cantarell", 1, 13)); // NOI18N
    titlePanel.setForeground(new java.awt.Color(0, 0, 0));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addComponent(iconPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, 0)
        .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
      .addComponent(iconPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel iconPanel;
  private javax.swing.JLabel titlePanel;
  // End of variables declaration//GEN-END:variables

  public void setSelected(boolean selected) {
    this.isSelected = selected;
    if (this.isSelected) {
      this.crrColor = new java.awt.Color(204, 204, 204);
    } else {
      this.crrColor = new java.awt.Color(153, 153, 153);
    }

    this.updateAppearance();
  }
  
  private void initialize() {
    this.titlePanel.setText(this.title);
    this.crrColor = new java.awt.Color(153, 153, 153);
    this.hoverColor = new java.awt.Color(192, 192, 192);

    this.setupMouseEvents();
  }

  private void setupMouseEvents() {
    String title = this.title;

    this.addMouseListener(new java.awt.event.MouseAdapter() {
      @Override
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        MenuCardPanel.this.isHovered = true;
        MenuCardPanel.this.updateAppearance();
      }

      @Override
      public void mouseExited(java.awt.event.MouseEvent evt) {
        MenuCardPanel.this.isHovered = false;
        MenuCardPanel.this.updateAppearance();
      }

      @Override
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        EventManager.getInstance().publish(new MenuItemSelectedEvent(title));
      }
    });
  }

  private void updateAppearance() {
    if(this.isHovered) {
      this.setBackground(this.hoverColor);
    } else {
      this.setBackground(this.crrColor);
    }

    this.repaint();
  }
}
