package com.doo.finalActv.beautymaker.view;

import java.util.EnumMap;
import javax.swing.JInternalFrame;


public class MainWindow extends javax.swing.JFrame {

  private enum AppView { 
    LOGIN,
    SIGNUP,
    HOME
  };
  
  private EnumMap<AppView, JInternalFrame> views;
  private AppView currentView;

  public MainWindow() {
    initComponents();
    this.startApplication();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jDesktopPane1 = new javax.swing.JDesktopPane();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setPreferredSize(new java.awt.Dimension(800, 600));

    javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
    jDesktopPane1.setLayout(jDesktopPane1Layout);
    jDesktopPane1Layout.setHorizontalGroup(
      jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 1080, Short.MAX_VALUE)
    );
    jDesktopPane1Layout.setVerticalGroup(
      jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 720, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jDesktopPane1)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jDesktopPane1)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JDesktopPane jDesktopPane1;
  // End of variables declaration//GEN-END:variables

  private void startApplication() {
    this.views = new EnumMap<>(AppView.class);

    this.showLoginView();
  }

  private void showLoginView() {
    this.currentView = AppView.LOGIN;
    this.updateView();
  }

  private void updateView() {
    if(this.views == null || this.currentView == null) {
      System.err.println("Views or current view is not initialized.");
      return;
    }

    for(JInternalFrame view : this.views.values()) {
      view.setVisible(false);
    }

    JInternalFrame target = this.views.computeIfAbsent(
        this.currentView,
        this::createFrame
    );
    if(target == null) {
      System.err.println("Failed to create view for: " + this.currentView);
      return;
    }

    target.setVisible(true);
    target.toFront();
  }

  private JInternalFrame createFrame(AppView view) {
    switch (view) {
      case LOGIN:
        JInternalFrame loginView = new LoginView();
        this.jDesktopPane1.add(loginView);
        return loginView;
      case SIGNUP:
        //TODO
        return null;
      case HOME:
        //TODO
        return null;
      default:
        return null;
    }
  }
}
